In [31]:
%load_ext autoreload
%autoreload 2

import warnings
warnings.simplefilter('ignore')

import pandas as pd
import numpy as np
import sys
import seaborn as sns
sys.path.append('../src/')
sys.path.append('../src/exp_010')
from preprocess import read_data, get_data

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [32]:
X_train, y, group, X_test, submit = get_data()

==================== start run blocks ====================
	- <preprocess.YLagLeadBlock object at 0x7fca164358d0> 0.462[s]
	- <preprocess.YLagLeadBlock object at 0x7fca1c1d2c50> 0.415[s]
	- <preprocess.YLagLeadBlock object at 0x7fca17458090> 0.420[s]
	- <preprocess.YLagLeadBlock object at 0x7fca0a06aa50> 0.423[s]
	- <preprocess.YLagLeadBlock object at 0x7fca0a06a990> 0.417[s]
	- <preprocess.YLagLeadBlock object at 0x7fca16fbf850> 0.418[s]
	- <preprocess.YLagLeadBlock object at 0x7fca16fbfe50> 0.417[s]
	- <preprocess.YLagLeadBlock object at 0x7fca16fbff50> 0.413[s]
	- <preprocess.YLagLeadBlock object at 0x7fca16fbfb10> 0.407[s]
	- <preprocess.YLagLeadBlock object at 0x7fca0a06a490> 0.474[s]
	- <preprocess.TargetEncodingBlock object at 0x7fca16fbfa50> 1.931[s]
	- <preprocess.TargetEncodingBlock object at 0x7fca16fbfad0> 1.946[s]
	- <preprocess.CountEncodingBlock object at 0x7fca16fd5a50> 1.581[s]
run test = False 9.770[s]
==================== start run blocks ====================
	- <preprocess.YLagLeadBlock object at 0x7fca164358d0> 0.018[s]
	- <preprocess.YLagLeadBlock object at 0x7fca1c1d2c50> 0.009[s]
	- <preprocess.YLagLeadBlock object at 0x7fca17458090> 0.009[s]
	- <preprocess.YLagLeadBlock object at 0x7fca0a06aa50> 0.009[s]
	- <preprocess.YLagLeadBlock object at 0x7fca0a06a990> 0.009[s]
	- <preprocess.YLagLeadBlock object at 0x7fca16fbf850> 0.009[s]
	- <preprocess.YLagLeadBlock object at 0x7fca16fbfe50> 0.009[s]
	- <preprocess.YLagLeadBlock object at 0x7fca16fbff50> 0.009[s]
	- <preprocess.YLagLeadBlock object at 0x7fca16fbfb10> 0.009[s]
	- <preprocess.YLagLeadBlock object at 0x7fca0a06a490> 0.009[s]
	- <preprocess.TargetEncodingBlock object at 0x7fca16fbfa50> 0.058[s]
	- <preprocess.TargetEncodingBlock object at 0x7fca16fbfad0> 0.059[s]
	- <preprocess.CountEncodingBlock object at 0x7fca16fd5a50> 0.116[s]
run test = True 0.348[s]

In [33]:
X_train.head()

,index,lat,lon,co_cnt,co_min,co_mid,co_max,co_var,o3_cnt,o3_min,...,TE_meanis_holiday@TargetEncodingBlock,TE_stdmonth@TargetEncodingBlock,TE_stdCountry@TargetEncodingBlock,TE_stddayofweek@TargetEncodingBlock,TE_stdis_holiday@TargetEncodingBlock,CE_year@CountEncodingBlock,CE_month@CountEncodingBlock,CE_day@CountEncodingBlock,CE_Country@CountEncodingBlock,CE_dayofweek@CountEncodingBlock
0,0,-27.46794,153.02809,38,0.749,2.590,2.633,0.850,29,2.397,...,59.394758,52.063447,26.415061,38.963900,38.884706,69007,13977,6541,5656,27990
1,1,-12.46113,130.84185,47,2.594,3.181,4.828,1.208,49,3.092,...,58.687640,51.534113,25.215408,38.502928,38.559531,69007,13977,6541,5656,27990
2,2,-37.81400,144.96332,17,1.190,1.197,2.200,0.248,123,0.736,...,59.666334,50.167974,25.760983,38.062440,37.940368,69007,13977,6541,5656,27990
3,3,-32.92953,151.78010,63,4.586,11.044,14.802,24.186,90,1.917,...,59.666334,50.167974,25.760983,38.062440,37.940368,69007,13977,6541,5656,27990
4,4,-31.95224,115.86140,47,4.689,8.681,11.100,10.011,83,0.349,...,58.687640,51.534113,25.215408,38.502928,38.559531,69007,13977,6541,5656,27990

In [34]:
X_train[[ col for col in X_train.columns if 'lag' in col]].describe()

,lag-10Country_date_mean_pm25@YLagLeadBlock,lag-7Country_date_mean_pm25@YLagLeadBlock,lag-3Country_date_mean_pm25@YLagLeadBlock,lag-2Country_date_mean_pm25@YLagLeadBlock,lag-1Country_date_mean_pm25@YLagLeadBlock,lag1Country_date_mean_pm25@YLagLeadBlock,lag2Country_date_mean_pm25@YLagLeadBlock,lag3Country_date_mean_pm25@YLagLeadBlock,lag7Country_date_mean_pm25@YLagLeadBlock,lag10Country_date_mean_pm25@YLagLeadBlock
count,191400.000000,191850.000000,192578.000000,192857.000000,193025.000000,192890.000000,192639.000000,192391.000000,191341.000000,190799.000000
mean,58.897009,58.949537,59.000804,59.037601,59.076651,59.045499,59.021676,59.046817,58.917370,58.862574
std,25.108129,25.147620,25.171165,25.203311,25.239228,25.238971,25.226977,25.201638,25.050129,24.973968
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,41.816273,41.828591,41.861750,41.851000,41.865000,41.852625,41.858667,41.902920,41.858667,41.858667
50%,53.971297,54.038636,54.049700,54.069600,54.087694,54.066680,54.065333,54.087694,54.066680,54.003743
75%,70.061589,70.015533,70.140500,70.191921,70.252000,70.191921,70.142000,70.188500,70.067444,70.015533
max,280.116000,280.116000,280.116000,280.116000,280.116000,280.116000,280.116000,280.116000,280.116000,243.609000

In [35]:
df_train, df_test, submit = read_data()
df_train.groupby('Country').City.agg(pd.Series.nunique).sort_values()

Country
Canada                     1
Croatia                    1
Netherlands                1
Bosnia and Herzegovina     2
Brazil                     2
Serbia                     2
Vietnam                    3
Germany                    3
Russia                     3
Belgium                    4
Chile                      4
France                     4
Israel                     4
United Kingdom             5
South Africa               5
Italy                      5
Hungary                    5
Thailand                   6
Australia                  6
Taiwan                     7
Iran                       8
Mexico                    10
Poland                    10
Spain                     11
Turkey                    11
South Korea               16
United States             17
India                     18
Japan                     26
China                     39
Name: City, dtype: int64

In [36]:
df_train[df_train['City'] == 'Novosibirsk'].Country

10438     Russia
11084     Russia
15383     Russia
15594     Russia
18184     Russia
           ...
177206    Russia
182353    Russia
186698    Russia
189154    Russia
191707    Russia
Name: Country, Length: 430, dtype: object